# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Manushree Sannathimmappa
description: "Hello! I'm Manushree, and I'm a Data Scientist. My portfolio focuses on projects that I've worked on, with a strong emphasis on business impact. I influence decision makers showcasing the data behavior and patterns."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "California, USA"
resume_url: /docs/Manushree Sannathimmappa Resume 2022.pdf
avatar_image: /img/ManushreeTS.jpeg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/manushree-sannathimmappa-58a2a029/" # Add your linkedln handle
github: "https://github.com/Manushree-Sannathimmappa"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

